[package]
name = "jest-lang"
version = "0.1.1"
authors = ["Brendon Bown <bhbochikens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.0"